repos:
  # Run unit tests (pytest)
  # - repo: local
  #   hooks:
  #     - id: pytest
  #       name: Run pytest
  #       entry: python -m pytest -q
  #       language: python
  #       pass_filenames: false
  #       additional_dependencies:
  #         - .        # installs your project into the hook env
  #       files: |
  #         (?x)^(
  #           src/.*\.py|
  #           tests/.*\.py
  #         )$
  # Black - code formatter
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3

  # Ruff - linter & import sorter (can replace/isort if you want)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
      - id: ruff-format

  # nbstripout - strip Jupyter notebook outputs before commit
  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout

  # Basic hygiene: end-of-file fixer & trailing whitespace
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
